@hostname = http://localhost:8080
@contactId = 

### GET all contacts
GET {{hostname}}/contacts

### GET single contact
GET {{hostname}}/contacts/{{contactId}}

### CREATE contact
POST {{hostname}}/contacts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@test.com",
    "favoriteColor": "blue",
    "birthday": "1990-01-01"
}

### UPDATE contact
PUT {{hostname}}/contacts/{{contactId}}
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@test.com",
    "favoriteColor": "red",
    "birthday": "1990-01-01"
}

### DELETE contact
DELETE {{hostname}}/contacts/{{contactId}}
